version: '2'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 443:443
    command: /bin/bash -c "nginx -g 'daemon off;'"
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        registry_external_url 'https://registry.gitlab.example.com'
        gitlab_rails['registry_enabled'] = true
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 8888
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
  registry:
    image: registry:2
    restart: always
